### ISSUE TITLE
Block Diagram for the System

### ISSUE THREAD

**Issue by razstvien01** [kcenizaj/StudentManagementSystem#5]
~ Download draw.io.
~ Make a folder called 'designs'.
~ Save the worked design there, named it 'block-diagram'.
~ Make a block diagram for the student management system.
~ Make sure to include all the features.

**Comment by kcenizaj** [comment]
Done na ya, ako nang na butang sa repository. Though, naa koy mga features nga gi add. :3

**Comment by razstvien01** [comment]
To changes:
~ create a branch called 'design-diagram'
   - git branch design-diagram  (himo branch)
   - git branch (will display the branches, if naa tong design-diagram then na himo siya)
   - git checkout design-diagram
   
~ Make your diagram like this:


![Image](https://github.com/kcenizaj/StudentManagementSystem/assets/104712580/bc62a1a3-3216-42e3-9ecb-0daa27797016)


~ rename the folder from 'Design' to 'design'

~ do PR (Pull Request)  [base: development] <- [compare: design-diagram]
